version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_ventas_despachos
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: citt_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network


  backend-ventas:
    build:
      context: ./Springboot-API-REST-VENTAS
    container_name: api_ventas
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/citt_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

  backend-despachos:
    build:
      context: ./Springboot-API-REST-DESPACHO
    container_name: api_despachos
    ports:
      - "8081:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/citt_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./front_despacho
    container_name: web_frontend
    ports:
      - "80:80"
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge