spring.application.name=Springboot-API-REST-VENTAS

# Configuración de la base de datos MySQL en AWS RDS
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT:localhost}:${DB_PORT:3306}/${DB_NAME:demo_db}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

# Configuración de Hibernate
spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
